version: 0.1.{build}
image:
    - Visual Studio 2017
before_build:
    - git submodule update --init --recursive
    - cmake .
build_script:
    - cmake --build . --config Release
artifacts:
    - path: src/Release
      name: artifacts
      type: zip